-- ============================================================
-- VENDOR RISK MATRIX
-- ============================================================

create table if not exists public.vendor_risk_matrix (
  id bigint generated by default as identity primary key,

  vendor text not null,
  material text not null,

  single_source boolean not null default false,
  frequent_backorder boolean not null default false,

  risk_level text not null
    check (risk_level in ('Low', 'Medium', 'High')),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint vendor_risk_matrix_vendor_material_unique
    unique (vendor, material)
);


-- ============================================================
-- INDEX
-- ============================================================

create index if not exists idx_vendor_risk_matrix_vendor
  on public.vendor_risk_matrix (vendor);

create index if not exists idx_vendor_risk_matrix_risk_level
  on public.vendor_risk_matrix (risk_level);


-- ============================================================
-- RLS
-- ============================================================

alter table public.vendor_risk_matrix enable row level security;


-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================

create or replace function public.update_vendor_risk_matrix_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists trg_vendor_risk_matrix_updated_at
on public.vendor_risk_matrix;


create trigger trg_vendor_risk_matrix_updated_at
before update on public.vendor_risk_matrix
for each row
execute function public.update_vendor_risk_matrix_updated_at();