create table if not exists public.vendor_evaluations (
  id bigint generated by default as identity primary key,

  category text not null,
  period text not null,
  year integer not null,

  vendor text not null,

  price numeric(5,2) not null,
  quality numeric(5,2) not null,
  actual_quantity_delivery numeric(5,2) not null,
  on_time_delivery numeric(5,2) not null,

  final_score numeric(5,2) not null,

  status text not null
    check (status in ('Good', 'Enough', 'Bad')),

  evaluation_pdf text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint vendor_evaluations_unique
    unique (
      category,
      period,
      year,
      vendor
    )
);


create index if not exists idx_vendor_evaluations_vendor
  on public.vendor_evaluations (vendor);


create index if not exists idx_vendor_evaluations_year_period
  on public.vendor_evaluations (
    year,
    period
  );


create index if not exists idx_vendor_evaluations_status
  on public.vendor_evaluations (status);


alter table public.vendor_evaluations
enable row level security;


create or replace function public.update_vendor_evaluations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


drop trigger if exists trg_vendor_evaluations_updated_at
on public.vendor_evaluations;


create trigger trg_vendor_evaluations_updated_at
before update on public.vendor_evaluations
for each row
execute function public.update_vendor_evaluations_updated_at();